### ISSUE TITLE
No pwm characteristic found

### ISSUE THREAD

**Issue by jeroenknoester** [crownstone/bluenet-example-android#1]
Wanneer ik de crownstone selecteer toast het "No PWM characteristic found on this device". Daarna gaat de applicatie naar zijn beginscherm.
![img_8067](https://cloud.githubusercontent.com/assets/7842163/16192289/a9f15512-36e8-11e6-8fd5-bd9af6e01b43.JPG)

![img_8068](https://cloud.githubusercontent.com/assets/7842163/16192292/ae41a180-36e8-11e6-9241-96e520c9fcf7.JPG)
Hoe kan ik deze fout verhelpen?

**Comment by eggerdo** [comment]
Hey, we are currently in a big update, so you probably got the new version of the android library and example project. To fix that, please checkout the following tags
1. bluenet-lib-android
   `cd <bluenet-lib-android path>`
   `git checkout -b v0.2.1`
2. bluenet-example-android
   `cd <bluenet-example-android path>`
   `git checkout -b v0.0.1`

Then first select `Build > Clean Project` in the Android Studio and try to run it again.

**Comment by jeroenknoester** [comment]
Hi, we ran the commands but still got the same problem.

**Comment by eggerdo** [comment]
Ok then I need some more info from you to debug your problem:
1. Download the [NRF Master Control Panel](https://play.google.com/store/apps/details?id=no.nordicsemi.android.mcp). Then using that app, scan for devices and connect to your device. Make a screenshot of the discovered services and paste it here.
2. In Android Studio, open the Android Monitor (with you phone connected to the computer) run the example app, try to connect, and copy paste everything between 
   `D/nl.dobots.bluenet.ble.core.BleCore: Discovering services ...` and `D/nl.dobots.bluenet.ble.extended.BleExt: ... discovery done` in a file and attach it here.

If you prefer you can also send it to dominik@almende.org instead of putting it here.

**Comment by eggerdo** [comment]
Oh well, the tag of the library was wrongly set too, please repeat again the following steps, before you follow my second post:

`cd <bluenet-lib-android path>`
`git checkout master`
`git branch -D v0.2.1`
`git checkout -b v0.2.1`
